# model parameters
CRITIC_HIDDEN_DIM: 16
CRITIC_NUM_HIDDEN_LAYER: 3
CRITIC_ACTIVATE: 'tanh'
CRITIC_BATCH_NORM: True
CRITIC_WEIGHT_INIT: True

ACTOR_HIDDEN_DIM: 4
ACTOR_NUM_HIDDEN_LAYER: 2
ACTOR_ACTIVATE: 'relu'
ACTOR_BATCH_NORM: True
ACTOR_WEIGHT_INIT: True

MAX_CRITIC_LR: 0.01
MIN_CRITIC_LR: 0.001
CRITIC_LR_DECAY: 0.001

MAX_ACTOR_LR: 0.01
MIN_ACTOR_LR: 0.001
ACTOR_LR_DECAY: 0.001

# Env parameters
r: 0.01
w: 1.0
BETA: 0.96
a_min: 1e-10
a_max: 18
a_size: 200
PI:
- 0.9
- 0.1
- 0.1
- 0.9
z_vals:
- 0.1
- 1.0


# seed
seed: 20

# Training parameters
MAX_ITERATION: 10000
REPORT_PER_ITERATION: 1000
ENV_GEN_STATE_SAMPLING: False
BATCH_SIZE: 32
ENV_TRANSITION_NUM_STEPS: 1

