# model parameters
CRITIC_HIDDEN_DIM: 16
CRITIC_NUM_HIDDEN_LAYER: 3
CRITIC_ACTIVATE: 'tanh'
CRITIC_BATCH_NORM: True
CRITIC_WEIGHT_INIT: True

ACTOR_HIDDEN_DIM: 4
ACTOR_NUM_HIDDEN_LAYER: 2
ACTOR_ACTIVATE: 'relu'
ACTOR_BATCH_NORM: True
ACTOR_WEIGHT_INIT: True

MAX_CRITIC_LR: 0.01
MIN_CRITIC_LR: 0.01
CRITIC_LR_DECAY: 0.001

MAX_ACTOR_LR: 0.01
MIN_ACTOR_LR: 0.001
ACTOR_LR_DECAY: 0.001

# Env parameters
BETA: 0.96
GAMMA: 1.5
ENV_STATE_SPACE_L: 0.001
ENV_STATE_SPACE_H: 2.5
ENV_ACTION_SPACE_L: 0
ENV_ACTION_SPACE_H: 1

# seed
seed: 20

# Training parameters
MAX_ITERATION: 10000
REPORT_PER_ITERATION: 1000
ENV_GEN_STATE_SAMPLING: True
BATCH_SIZE: 32
ENV_TRANSITION_NUM_STEPS: 1
SOFT_UPDATE_TARGET_NET_TAU: 0.01
